### ISSUE TITLE
[FEATURE] Rearrange, insert & remove params from windows

### ISSUE THREAD

**Issue by Falki-git** [Micrologist/MicroEngineer#4]
Would be nice to have what KER has, ability to arrange window information as you want

**Comment by Micrologist** [comment]
This is planned but requires some major rewriting before doing it.

**Comment by Falki-git** [comment]
@Micrologist, if you don't have immediate plans to tackle this, I'd like to try it, if that's ok with you.

Was thinking on working on rearranging, adding/removing items in a window, as well as having an ability to create custom windows.

**Comment by Micrologist** [comment]
Got busy with real life for a bit, sorry.
What I had in mind was abstracting the sections/windows into a class that holds the relevant information like title, popoutstate / popout position and a list of entries (where each entry has a name and a reference to the value it should display).
Also the whole value gathering and calculating should be moved to `Update` since `OnGUI` might be called multiple times per frame and there is no situation where recalculating readouts multiple times is a useful thing to do.
