### ISSUE TITLE
Windows disappearing when popped out

### ISSUE THREAD

**Issue by James-Dumas** [Micrologist/MicroEngineer#40]
The Maneuver and Target windows completely disappeared when I clicked the pop-out icon on them, and there seems to be no way to get them back from the settings menu. Every other built-in window plus a custom window did not disappear when popped out.

Edit: I realized after playing for a bit that the Maneuver window reappears when a maneuver is created, and disappears when all maneuvers are deleted. Same for the Target window when setting/unsetting a target. I'm not sure if this is intended behavior, but it seems unintuitive to me. I think there should at least be a way to reset a popped out window even when it can't be seen.

**Comment by Falki-git** [comment]
Hey @James-Dumas, this is the intended behavior. It was done to declutter the UI if there are no valid Maneuvers and/or Targets. 

They don't hide in the main GUI so that players are aware that the Maneuver and Targets windows exist. There are many entries available and one the issues is that players are not aware of all the possibilities that MicroEngineer provides (since many entries are hidden by default so that they don't clutter the UI), so some actions were taken to "promote" the existance of certain things.

Thanks for reaching out!
