### ISSUE TITLE
C.A. Dist. 1 does not update in craft view when burning

### ISSUE THREAD

**Issue by alex-sherwin** [Micrologist/MicroEngineer#48]
C.A. Dist. 1 does not update in craft view when burning

If you burn with Micro Engineer open in Map view, the C.A. Dist. 1 value updates live while burning

But if you burn w/ Micro Engineer open in Craft view, the C.A. Dist. 1 value does not update while burning

Example clip: https://youtube.com/clip/Ugkxx1TOTxsjpND-VZhd-3ce_VJrcS89UeHZ?si=YvohJQnvYE9u8TqS

Would be nice if it updated in Craft view so you can do some, for example, accurate rendezvous maneuvers in Craft

**Comment by Falki-git** [comment]
Thanks for the report.
99% of what Micro Engineer is doing is taking data that the game already calculates and it displays it. Certain values the game is only updating in certain views. Close Approach data seems to be one of those. I'll need to see if it's possible to get those values in Flight view, but I doubt it.
Personally, I do orbital changes and rendezvous in Map view, since it's more intuitive to see your flight path changing as you perform trajectory planning and execute burns, so I didn't feel a need to have that data displayed in Flight. But I certainly understand your preference.

**Comment by Falki-git** [comment]
Well, kinda? But it's hard to consider this as a bug from the game's standpoint. They're using it to display close approach stats when you're in Map view, so it makes sense they're updating it only when Map is turned on. I'll try to see if there's another way to get that.

**Comment by Falki-git** [comment]
Added new entries in https://github.com/Falki-git/MicroEngineer/pull/34
New close approach entries will now update in Flight view also.
